name: Run Click Pirate Bot

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:  # lets you run manually too

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run the bot
        run: python telegram_click_pirate_bot.py
